name: tutorials

channels:
  - astropy

dependencies:
  - python=3.6
  - IPython=6.1.0
  - astropy=2.0
  - astroquery=0.3.6
  - matplotlib=2.0.2
  - numpy=1.13.1
  - scipy=0.19 # needed for coordinates cross-matching
  - jupyter=1.0
  - notebook=5.0
  - aplpy=1.1.1
  - spectral-cube=0.4
  - reproject=0.3.2
  - pip:
    - git+https://github.com/jupyter/nbconvert # this is really >=5.4, but at the time of adding this that wasn't yet available
